# Generated by Django 5.2.9 on 2025-12-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermons'},
        ),
        migrations.AddField(
            model_name='sermon',
            name='scripture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sermons/thumbnails/'),
        ),
    ]
