# Generated by Django 5.2.9 on 2025-12-04 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_attendance_data_forward(apps, schema_editor):
    OldAttendance = apps.get_model("attendance", "Attendance")
    AttendanceSheet = apps.get_model("attendance", "AttendanceSheet")
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")

    # Map old IDs to new sheet IDs
    id_map = {}

    # Copy each old attendance row to new AttendanceSheet
    for old in OldAttendance.objects.all():
        new_sheet = AttendanceSheet.objects.create(
            date=old.date,
            type=old.type if hasattr(old, "type") else "service",
            total_present=old.total_present if hasattr(old, "total_present") else 0,
            event=getattr(old, "event", None),
            group=getattr(old, "group", None),
            recorded_by=getattr(old, "recorded_by", None),
            sermon=getattr(old, "sermon", None),
        )
        id_map[old.id] = new_sheet.id

    # Update AttendanceRecord.attendance_id
    for rec in AttendanceRecord.objects.all():
        if rec.attendance_id in id_map:
            rec.attendance_id = id_map[rec.attendance_id]
            rec.save()


def migrate_attendance_data_backward(apps, schema_editor):
    # No backward migration needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        (
            "events",
            "0002_remove_event_is_global_event_banner_event_created_at_and_more",
        ),
        ("groups", "0002_ministrygroup_created_at_groupmembership"),
        ("sermons", "0002_alter_sermon_options_sermon_scripture_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sermon", "Sermon"),
                            ("event", "Event"),
                            ("service", "Sunday Service"),
                            ("fellowship", "Fellowship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_present", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="groups.ministrygroup",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sermon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sermons.sermon",
                    ),
                ),
            ],
        ),
        # 🟢 INSERT DATA MIGRATION HERE BEFORE FK ALTER
        migrations.RunPython(
            migrate_attendance_data_forward, migrate_attendance_data_backward
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.attendancesheet",
            ),
        ),
        migrations.DeleteModel(name="Attendance"),
    ]
